package tn.esprit.medicaltourism.test;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

import tn.esprit.medicaltourism.domain.User;
import tn.esprit.medicaltourism.initDB.InitdbRemote;

import com.alee.laf.WebLookAndFeel;



public class Connection extends JFrame {
	

	private java.sql.Connection connection;
	private InitdbRemote initdbRemote;
	

	public Connection() {
		setAlwaysOnTop(true);
		WebLookAndFeel.install();
		try {
			Context ctx = new InitialContext();
			initdbRemote = (InitdbRemote) ctx
					.lookup("/medicaltourismEJB/Initdb!tn.esprit.medicaltourism.initDB.InitdbRemote");
		} catch (NamingException e1) {
			e1.printStackTrace();
		}
		initComponents();
//		changeIcon();
		this.setLocationRelativeTo(null);
		
		

	}
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		Tf_pseudo = new javax.swing.JTextField();
		Tf_pseudo.setBounds(205, 189, 233, 32);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Medical Tourism");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setMinimumSize(new java.awt.Dimension(258, 420));
		setName("b"); // NOI18N
		setResizable(false);
		login_btn = new javax.swing.JLabel();
		login_btn.setBounds(245, 403, 148, 42);
		login_btn.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/Blue Button.png")));
		login_btn.setBackground(Color.BLUE);
		login_btn.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				login_btn.setIcon(new ImageIcon("C:\\Users\\firasniper\\Desktop\\Blue Button.png"));
				User found = initdbRemote.authentificate(Tf_pseudo.getText(), String.valueOf(Tf_Mdp.getPassword()));
			
			if (found == null) {
				System.out.println("bad credentials!");
									
			}else{
				
//				if(found instanceof Admin){
//					EventQueue.invokeLater(new Runnable() {
//						public void run() {
//							try {
//								AdminUI frame = new AdminUI();
//								frame.setVisible(true);
//							} catch (Exception e) {
//								e.printStackTrace();
//							}
//						}
//					});
//				}else if(found instanceof Employee){
//					EventQueue.invokeLater(new Runnable() {
//						public void run() {
//							try {
//								EmployeeUI frame = new EmployeeUI();
//								frame.setVisible(true);
//							} catch (Exception e) {
//								e.printStackTrace();
//							}
//						}
//					});
//				}
			dispose();
				System.out.println("OK");
				Backoffice  backoffice=new Backoffice() ;
				backoffice.setVisible(true);
				
			}
			
		}
			@Override
			public void mouseEntered(MouseEvent e) {
				ImageIcon button_hover = new ImageIcon("C:\\Users\\firasniper\\Desktop\\hover.png");
				login_btn.setIcon(button_hover);
			}
			@Override
			public void mouseExited(MouseEvent e) {
				ImageIcon button_hover = new ImageIcon("C:\\Users\\firasniper\\Desktop\\Blue Button.png");
				login_btn.setIcon(button_hover);
				
			}
		});
				jPanel1.setLayout(null);
				
				admin_lb = new JLabel("admin_label");
				admin_lb.addMouseListener(new MouseAdapter() {
					@Override
					public void mouseEntered(MouseEvent e) {
						admin_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/admin pressed.png")));
					}
					@Override
					public void mouseExited(MouseEvent e) {
						
						admin_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/admin.png")));

					}
				});
				admin_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/admin.png")));
				admin_lb.setBounds(415, 484, 102, 105);
				jPanel1.add(admin_lb);
				
				consultant_lb = new JLabel("consultant_label");
				consultant_lb.addMouseListener(new MouseAdapter() {
					@Override
					public void mouseEntered(MouseEvent e) {
						consultant_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/consultant pressed.png")));
					}
					@Override
					public void mouseExited(MouseEvent e) {
						consultant_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/consultant.png")));
					}
				});
				consultant_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/consultant.png")));
				consultant_lb.setBounds(314, 484, 96, 105);
				jPanel1.add(consultant_lb);
				
				JLabel doctor_lb = new JLabel("");
				doctor_lb.addMouseListener(new MouseAdapter() {
					@Override
					public void mouseEntered(MouseEvent e) {
						doctor_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/doctor pressed.png")));
					}
					@Override
					public void mouseExited(MouseEvent e) {
						doctor_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/doctor.png")));
					}
				});
				doctor_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/doctor.png")));
				doctor_lb.setBounds(212, 484, 96, 105);
				jPanel1.add(doctor_lb);
				
				JLabel client_lb = new JLabel("client_label");
				client_lb.addMouseListener(new MouseAdapter() {
					@Override
					public void mouseEntered(MouseEvent e) {
						client_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/user pressed.png")));
						
					}
					@Override
					public void mouseExited(MouseEvent e) {
						client_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/user.png")));
					}
				});
				client_lb.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/user.png")));
				client_lb.setBounds(111, 489, 89, 94);
				jPanel1.add(client_lb);
				jLabel2 = new javax.swing.JLabel();
				jLabel2.setBounds(205, 153, 81, 23);
				
						jLabel2.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
						jLabel2.setForeground(new java.awt.Color(255, 255, 255));
						jLabel2.setText("Nick name :");
						jPanel1.add(jLabel2);
				Tf_Mdp = new javax.swing.JPasswordField();
				Tf_Mdp.setBounds(205, 274, 220, 31);
				
						Tf_Mdp.setText("root");
						jPanel1.add(Tf_Mdp);
				jLabel3 = new javax.swing.JLabel();
				jLabel3.setBounds(215, 238, 102, 23);
				
						jLabel3.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
						jLabel3.setForeground(new java.awt.Color(255, 255, 255));
						jLabel3.setText("Password :");
						jPanel1.add(jLabel3);
		
//				signup.setIcon(new javax.swing.ImageIcon(getClass().getResource(
//						"/dao/gui/images/image (1).png"))); // NOI18N
				login_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
				client_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
				admin_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
				consultant_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
				doctor_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

				jPanel1.add(login_btn);

		Tf_pseudo.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
		Tf_pseudo.setText("root");
		
		jPanel1.add(Tf_pseudo);
		
		JLabel lblBackground = new JLabel("");
		lblBackground.setBounds(0, 0, 626, 626);
		lblBackground.setIcon(new ImageIcon(Connection.class.getResource("/edu/esprit/medicaltourism/images/images/darkerlight.jpg")));
		jPanel1.add(lblBackground);
		GroupLayout groupLayout = new GroupLayout(getContentPane());
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 626, GroupLayout.PREFERRED_SIZE)
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 626, GroupLayout.PREFERRED_SIZE)
		);
		getContentPane().setLayout(groupLayout);

		pack();
	}// </editor-fold>

//	public void changeIcon() {
//		URL url = getClass().getResource("/dao/gui/images/e.png");
//		ImageIcon icon = new ImageIcon(url);
//		java.awt.Image image = icon.getImage();
//		this.setIconImage(image);
//	}

	/**
	 *
	 * @param args
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Connection.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Connection.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Connection.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Connection.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
//		try {

//			JSplash splash = new JSplash(
//					Connection.class.getResource("eventologo.png"), true, true,
//					false, "", null, Color.BLUE, Color.BLACK);
//			splash.setAlwaysOnTop(true);
//			splash.splashOn();
//			splash.setProgress(20, "");
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {

					new Connection().setVisible(true);
				}
			});
			// splash.setProgress(20, "");
			// Thread.sleep(500);
			// splash.setProgress(40, "");
			// Thread.sleep(500);
			// splash.setProgress(60, "");
			// Thread.sleep(500);
//			splash.setProgress(80, "");
//			Thread.sleep(500);
//			splash.splashOff();
//		} catch (Exception ex) {
//			System.out.println(ex);
//		}
	}

	// Variables declaration - do not modify
	private javax.swing.JPasswordField Tf_Mdp;
	private javax.swing.JTextField Tf_pseudo;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel login_btn;
	private JLabel consultant_lb;
	private JLabel admin_lb;
}
